server:
  port: 8001

spring:
  application:
    name: authorize-center
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    url: jdbc:mysql://localhost:3306/authorize_center?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: qianniaomysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      idle-timeout: 180000
  data:
    mongodb:
      host: localhost
      port: 27017
      database: authorize_center

  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  file.max-history: 2
  file.max-size: 100MB
  file:
    path: /data/logs/authorize-center/
  level:
    root: info
    com:
      nexgo: info
